sonar.projectKey=Les-Patricks_site-BDD
sonar.organization=les-partricks
sonar.sources=js
sonar.tests=js/tests
sonar.test.inclusions=js/tests/**/*.test.js
sonar.exclusions=**/node_modules/**,**/vendor/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
