import { describe, it, expect } from "vitest";

import { buildSupabaseConfigModuleContents } from "../../scripts/write-supabase-config.mjs";

describe("buildSupabaseConfigModuleContents", () => {
	it("includes JSON-stringified URL and anon key as valid ES module exports", async () => {
		const url = "https://proj.supabase.co";
		const key = 'anon-with-"-quote-and-\\-backslash';
		const src = buildSupabaseConfigModuleContents(url, key);
		const mod = await import(
			`data:text/javascript;charset=utf-8,${encodeURIComponent(src)}`,
		);
		expect(mod.supabaseUrl).toBe(url);
		expect(mod.supabaseAnonKey).toBe(key);
	});

	it("uses https URL shape in fixture line for smoke check", () => {
		const src = buildSupabaseConfigModuleContents(
			"https://x.supabase.co",
			"eyJ0eXAiOiJKV1QifQ.stub",
		);
		expect(src).toContain('export const supabaseUrl = "https://x.supabase.co"');
		expect(src).toContain("export const supabaseAnonKey = ");
		expect(src).toContain("Generated by scripts/write-supabase-config.mjs");
	});
});
